export const ERROR_MESSAGES = {
  courseName: "Course name is required",
  courseYear: "Course year is required",
  courseStream: "Course stream is required",
  courseType: "Course type is required",
  courseCode: "Course code is required",
  subjectCode: "Subject code is required",
  subjectName: "Subject name is required",
  subjectIcon: "Subject icon is required",
  chapterCode: "Chapter code is required",
  chapterName: "Chapter name is required",
  topicCode: "Topic code is required",
  topicName: "Topic name is required",
  topicIcon: "Topic icon is required",
  boardCode: "Board code is required",
  boardName: "Board name is required",
  chapterIcon: "Chapter icon is required",
  firstName: "First name is required",
  lastName: "Last name is required",
  userName: "Username is required",
  email: "Email is required",
  mobileNo: "Mobile No. is required",
  role: "Role is required",
  city: "City is required",
  state: "State is required",
  pincode: "Pincode is required",
}